
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 's\xa1\x8a\xdd4)\x1a@\xbc@V\x97@\x8e\x9f\x8d'
    
_lr_action_items = {'WORD':([0,3,4,8,9,],[1,1,1,1,1,]),'NUMBER':([0,3,4,8,9,],[2,2,2,2,2,]),'OPERATOR':([1,2,5,6,7,10,11,],[-1,-2,8,-5,8,-4,8,]),'COMMA':([1,2,6,7,10,11,],[-1,-2,-5,9,-4,-3,]),'NOT':([0,3,4,8,9,],[3,3,3,3,3,]),'QUANTIFIER':([0,3,4,8,9,],[4,4,4,4,4,]),'$end':([1,2,5,6,10,11,],[-1,-2,0,-5,-4,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,4,8,9,],[5,6,7,10,11,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> WORD','expression',1,'p_expression_wordornumber','propParser.py',10),
  ('expression -> NUMBER','expression',1,'p_expression_wordornumber','propParser.py',11),
  ('expression -> QUANTIFIER expression COMMA expression','expression',4,'p_expression_quantifier','propParser.py',15),
  ('expression -> expression OPERATOR expression','expression',3,'p_expression_op','propParser.py',19),
  ('expression -> NOT expression','expression',2,'p_expression_not','propParser.py',23),
]
